### ISSUE TITLE
doesn't respect `ignore-pattern` in `pyproject.toml`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/vscode-pylint#169]
```toml
[tool.pylint.MASTER]
ignore-patterns = '.*\.pyi'
```
![image](https://user-images.githubusercontent.com/57028336/186063270-9e0c2152-5672-4270-b534-094b763bf73e.png)
